version: '2'

services:
  ordering.api:
    image: eshop/ordering.api${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionString=Server=ordering.data;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word
    ports:
      - "81:80"
    depends_on:
      - ordering.data

  ordering.data:
    image: microsoft/mssql-server-linux
	environment:
	  - ACCEPT_EULA=Y
	  - SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"