version: '3.4'

services:

  basket.api:
    image: eshop/basket.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile    
    depends_on:
      - basket.data
      - identity.api
      - rabbitmq

  catalog.api:
    image: eshop/catalog.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  identity.api:
    image: eshop/identity.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Identity/Identity.API/Dockerfile    
    depends_on:
      - sql.data

  ordering.api:
    image: eshop/ordering.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Ordering/Ordering.API/Dockerfile    
    depends_on:
      - sql.data
      - rabbitmq

  marketing.api:
    image: eshop/marketing.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Marketing/Marketing.API/Dockerfile    
    depends_on:
      - sql.data
      - nosql.data
      - identity.api
      - rabbitmq

  webspa:
    image: eshop/webspa:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebSPA/Dockerfile    
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api

  webmvc:
    image: eshop/webmvc:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebMVC/Dockerfile    
    depends_on:
      - catalog.api
      - ordering.api
      - identity.api
      - basket.api
      - marketing.api

  webstatus:
    image: eshop/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/WebStatus/Dockerfile

  payment.api:
    image: eshop/payment.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq    
    
  locations.api:
    image: eshop/locations.api:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/Location/Locations.API/Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3-management-alpine

  apigw:
    image: eshop/ocelotapigw
    build:
      context: .
      dockerfile: src/Apigw/OcelotApiGw/Dockerfile

#  mobilebff.marketing.apigw:
#    image: eshop/ocelotapigw
#    build:
#      context: .
#      dockerfile: src/Apigw/OcelotApiGw/Dockerfile

#  mobilebff.shopping.apigw:
#    image: eshop/ocelotapigw
#    build:
#      context: .
#      dockerfile: src/Apigw/OcelotApiGw/Dockerfile

#  webbff.marketing.apigw:
#    image: eshop/ocelotapigw
#    build:
#      context: .
#      dockerfile: src/Apigw/OcelotApiGw/Dockerfile

#  webbff.shopping.apigw:
#    image: eshop/ocelotapigw
#    build:
#      context: .
#      dockerfile: src/Apigw/OcelotApiGw/Dockerfile

  mobilebff.marketing.httpaggregator:
    image: mobilebff.marketing.httpaggregator
    build:
      context: .
      dockerfile: src/ApiGateways/MobileBff.Marketing/MobileBff.Marketing.HttpAggregator/Dockerfile


  mobilebff.shopping.httpaggregator:
    image: mobilebff.shopping.httpaggregator
    build:
      context: .
      dockerfile: src/ApiGateways/MobileBff.Shopping/MobileBff.Shopping.HttpAggregator/Dockerfile


  webbff.marketing.httpaggregator:
    image: webbff.marketing.httpaggregator
    build:
      context: .
      dockerfile: src/ApiGateways/WebBff.Marketing/WebBff.Marketing.HttpAggregator/Dockerfile


  webbff.shopping.httpaggregator:
    image: webbff.shopping.httpaggregator
    build:
      context: .
      dockerfile: src/ApiGateways/WebBff.Shopping/WebBff.Shopping.HttpAggregator/Dockerfile

