#
# docker-compose.yml is used to set up the base config per container to be deployed
# Take into account that when deploying, this base configuration is merged with the 
# configuration-per-environment specified at the docker-compose.override.yml
# Further details and docs: https://docs.docker.com/compose/extends/ 
#
version: '2'

services:
  webmvc:
    image: eshop/web
    depends_on:
      - identity.service
      - basket.api

  webspa:
    image: eshop/webspa
    depends_on:
      - basket.api
      - identity.service

  basket.api:
    image: eshop/basket.api
    depends_on:
      - basket.data
      - identity.service

  catalog.api:
    image: eshop/catalog.api
    depends_on:
      - business.data

  ordering.api:
    image: eshop/ordering.api
    depends_on:
      - business.data

  identity.service:
    image: eshop/identity
    depends_on:
      - identity.data

  identity.data:
    image: microsoft/mssql-server-linux

  business.data:
    image: microsoft/mssql-server-linux

  basket.data:
    image: redis
