version: '2'

services:
  basket.api:
    image: user/basket.api${TAG}
    environment:
      - ConnectionString=basket.data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "32783:80"
    depends_on:
      - basket.data

  basket.data:
    image: redis

  identity.service:
    image: eshop/identity
    expose:
      - "80"
    ports:
      - "5105:80"
    depends_on:
      - identity.data
      
  identity.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
